config/routes.rb
Bitcharity::Application.routes.draw do
  get "faq/index"
  resources :charities

  get "home/index"

  devise_for :users, controllers: { sessions: "session" }

  root 'home#index'

  get "dashboard" => "dashboard#index"
  post "dashboard" => "dashboard#selectPrimary"
  post "accounting" => "accounting#processPayment"

  get "faq" => "faq#index"

end

app/models/charity.rb
class Charity < ActiveRecord::Base
  has_many :users
  has_many :transactions
end

app/controllers/charities_controller.rb
class CharitiesController < ApplicationController
  before_action :set_charity, only: [:show, :edit, :update, :destroy]

  # GET /charities
  # GET /charities.json
  def index
    @charities = Charity.all
  end

  # GET /charities/1
  # GET /charities/1.json
  def show
  end

  # GET /charities/new
  def new
    @charity = Charity.new
  end

  # GET /charities/1/edit
  def edit
  end

  # POST /charities
  # POST /charities.json
  def create
    @charity = Charity.new(charity_params)

    respond_to do |format|
      if @charity.save
        format.html { redirect_to @charity, notice: 'Charity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @charity }
      else
        format.html { render action: 'new' }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charities/1
  # PATCH/PUT /charities/1.json
  def update
    respond_to do |format|
      if @charity.update(charity_params)
        format.html { redirect_to @charity, notice: 'Charity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @charity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charities/1
  # DELETE /charities/1.json
  def destroy
    @charity.destroy
    respond_to do |format|
      format.html { redirect_to charities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_charity
      @charity = Charity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def charity_params
      params.require(:charity).permit(:name, :description, :logo, :url)
    end
end

app/helpers/charities_helper.rb
module CharitiesHelper
end

app/views/charities/_form.html.erb
<%= form_for(@charity) do |f| %>
  <% if @charity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@charity.errors.count, "error") %> prohibited this charity from being saved:</h2>

      <ul>
      <% @charity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br>
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charities/edit.html.erb
<h1>Editing charity</h1>

<%= render 'form' %>

<%= link_to 'Show', @charity %> |
<%= link_to 'Back', charities_path %>

app/views/charities/index.html.erb
<h1>Listing charities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Logo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @charities.each do |charity| %>
      <tr>
        <td><%= charity.name %></td>
        <td><%= charity.description %></td>
        <td><%= charity.logo %></td>
        <td><%= link_to 'Show', charity %></td>
        <td><%= link_to 'Edit', edit_charity_path(charity) %></td>
        <td><%= link_to 'Destroy', charity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Charity', new_charity_path %>

app/views/charities/new.html.erb
<h1>New charity</h1>

<%= render 'form' %>

<%= link_to 'Back', charities_path %>

app/views/charities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @charity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @charity.description %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @charity.logo %>
</p>

<%= link_to 'Edit', edit_charity_path(@charity) %> |
<%= link_to 'Back', charities_path %>