config/routes.rb
Bitcharity::Application.routes.draw do
  get "faq/index"
  resources :charities

  get "home/index"

  devise_for :users, controllers: { sessions: "session" }

  root 'home#index'

  get "dashboard" => "dashboard#index"
  post "dashboard" => "dashboard#selectPrimary"
  post "accounting" => "accounting#processPayment"

  get "faq" => "faq#index"

end

app/views/layouts/_user_header.html.erb
<link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<div class="navbar-collapse collapse">

  <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Total Donated: #{coinbase.balance.format} ($#{number_with_precision(coinbase.balance.to_f*coinbase.buy_price(1).to_f, :precision => 2)})", faq_path %></li>
      <li><%= link_to "Questions", faq_path %></li>
    <% if user_signed_in? %>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
      <li><%= link_to "Sign in", new_user_session_path %></li>
      <li><%= link_to "Sign up", new_user_registration_path %></li>
    <% end %>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>GiveBit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Give<span class="blue">Bit</span></a>
      </div>
      <%= render 'layouts/user_header' %>
    </div>
</nav>

<div class="container-fluid" id="content">
  <div id= "notice">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>
  </div>
</div>
<%= yield %>

</body>
</html>